env:
  global:
    - secure: CFbLsH7w9Ez8LBc3iIQCZqRNCnmfvAjANFeTV5jEejTRIycj52rCW8OGsom8PCWEqIWoBspSZbpRnlIpyHl94kbMRDCe/X0dQP6MFVw8dmVFGXBLRuL8z9BifmVJMRaKMVUULHVb6yxn/qnVwGlRIvuBOS+CtPVp+JRgdIVtJm1Ngpfp7fPPdp0fHRGNlJpO8vLwc58ZdCUx8oyxQD3UsGeFJSyjxDh20bzFlmQztbJSML0ntPwqXztnoLs0sfGg5LEwJi0U6ggzTtpy9c0RoRZDc0yjL4dyNlmI0qV2BAjMS9MtGoYLDi+Vi8ys1Yu5bDMP48dzA75fPw8JmgQnYY92pWAwkMsD5Xw2XlOJdnx9ask8QIvMiJzMZovDSnd6/tPJHiaPz2ozHBwi+v9yJ5j+tVg+vupTuQqbaDFv23n8FaHrFvc+V2SQ8XKXg2tGpoGewQr9HmMDE7khDXjzJ79iTK8rqmiiErgu0jHTG+O3QEdvrYVb+Cw3KjwEiC6I4sk/IDA3sFHFtY25JcVHIKnp2bq0vuJdmZ3qfB1NP7OfNJffqZTSGVdwEvNB0cG0kQ1Vu1rtqxovN57pq/bKyIEphImZplBG/Skb7OaJUM6tokvF/aY9E6T9+fXTjqobgNDFPR4/09M7YswM5Ug9YEsASux2zKBY5pbdKZvGLK4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_4
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
