env:
  global:
    - secure: P+vvzXj1FHyNnkvt2JGslZFlUXcAa1jiDhBJJSBJg2oRGmcTOqpBHVZ201yph2WgPGRi4E3LZS1YHKbML3TJ68yJo33v7ey6QuIm+bvgUaSdLHOFZi3KBsnAta7xSin3lwXcK4RjiIGR90F+mBR79ZfDMgCYbRZX5lOG1IX8JbI65fHq4mPmi1lU9I3k2zQ7IiB/KWIGvPaQrCQvFUlrm1SUrBTw3rr/kb/o4pIAjledNWlZpDunhPdttQWZZ3qrsJeIBjBjngTIuqQ0dDnZRnDyddfn+0+OS9qTD4W1MaPj1xOo6CjO1sO/KytdV5KFzZhXJ4/KFAlKBOrWNkSYBgIWy0D3a1bHAk6Z6FzKbMI2ObYqyEZTh1LkKW9yJY+snTq8vlufTv2g3cJHjWAzZMt/4Qf6lzjpOfNU7iCzplbTv+Plyc4NmrBvzJhGGZ4pqj7fqX8pKTF//DiZhsDOtP0HXwZvZoik7uxXfrF8YiWevhJXLej7FAt8f3lX6Q0PHiu753+DFywNjz3gUYX9Ms3GILlXQWALU6STCFKdP1KSufDeIPY137lgFeYv0GX/7lyi2w2fycj7ldO/RFEu+nPI0AwL/AlJsKymRuemX/iwfb45mluKlSbU3zkK5G5gZHdD/SCovOvRXCRpTMcM6QfCGjzFKizxue91Nhq1g0o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_4
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
