env:
  global:
    - secure: NTbxIgilrOlBJIvuzMZT8njDtQdq/8j5urkqvoMIYIchV8RnHD/ojXMeMWb/hFtaDwOHrVA4Gk+4e1eUaPauxEsySvURwdZIojL0vOOuROGgVt6+y7kUqJqcaZqTv9tt/VmBqzWODEoyCq+dtVkFDUgrNNx+sTiRL5Caj70wILSbHTcWoTzOr4k/nza1abC1XEnCIbUTcm4GJxyE3XzR1etc0bSLxcjvJWqgMZXvlRwgJUNW8nvWUFd7o2Yu/JIdUz1TEGumhNZ0KKaoheO1cUhxb8s0dHzMPVbtlIbGZDJWoQn1RKiKJvu3sWJ1Pg5cL6c+DUP8enNHWLq68MYcPNEdqJ/IaNzAYCTS5rTGdd515SniPOg4yIi66arm7jcO+CixxKXIIT7R7d4Iau4aelN6qufYdDmYNilKYxxo/iZP751om9Vl4xsqFQCeoi8YzE6LVSPlkNW5H7YQPPXbtjeXZnoF0oj/KYQm8IGdpUIYPhho8QSwI5gYtTwt4gEfEjydrJjTzR5SFh/1UrrMfGqh7NErcwUhJD5QxP+Eb2MgCoNSO6y6uh5GfHCtAmSBz0y+w7NlwLT6Q79doIYmXxrwe6nGKY+yg7ogECdXckQwmLQYbBcoA3X+J5DSoo9ht7nWOtUof6LkYsLmtULzJk1NrYqUrOE8tHYMpDYx/go=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_4
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
