env:
  global:
    - secure: Tf9Yv6Ioz7tvywctaPQWj4DHa4b7jnwNuzHhyrNMCC7Wskz3OnDxkpflpNvaLOk5Z8cBfunTGk7omHCwnNaG9ICYGJwHYAum2fEdDCpb/Oaktc5M/GhY6u5LYcZSyznTnCoE0La3+G2ZSz5YOZ/JwvGNmTivKt2i+Yhtz0F4KUylrWDVO7ikJhheCbeGnKrQe4u3FTMxrVpDB16QaqIh4qsZhOIjbh9GvHH3ZCOCiF28IV6d9vZJNiCoeRrdoVeKxy6T6CHxRTeQgroLMepYJGtXso/lN6JNy/gH8gQkxtg3PftW2RShvzet7U6NdDTuA3PnIDV19y5oBPHLJMicKeWAY0H4G8N7IFNc9HpSlpXDjUyy4d0mF+bK++BLI+4tg62350yRGXoSZ/165+mkwn1kajSCcX3evEFvSGuMM4gP2Gs/tEke13tZW1vYDYpIJpaL+OaY3vOCYYq7hNjVSk9+LngKBh1Nny7vdyp6cy9hPyzDN3W8JhvtjTP9YzmpJOCI2GhQgb8brwuDKLwLc5k7wN9+hQSc1UJaJe7Q77uav4J1956bSRnUNDX8GuydD61DhJ/GDqpwJF2XVE2rJwpCYOnW+/NJ5WKfg9n7QS82FDNj0rRgQLA3TR869KRAxx5t9KDT9cS+/9VUIEInT2Br1pyQO9AS+z9jHaGUsPI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_4
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
