env:
  global:
    - secure: JScBxEgEmm/pINIeOOpJyVuBNAbZ+0D1fdVePkis1mYgCJNYvecHimMfXW5JLlTlcStCq3MYdK/3k13kAbjLFFl0wS27scNDghl0fkwhTr8P08Ggb7gowSbfMjB7rI0/h5Daj91Eya0mIZa6/Xq1Y0aBWUZlEUFyhB6UoYTPutKmY2AJIPp/Cjki3/gAk/qpjcG/vO8lyB5kTWVOiG/mxTPpZLyK4v7cD5tlNIedqLbfnnjZPa4v1kx+v8MK0ANUPPCAyVeJiN2s4YA38Vjdvehr2OtbcdErNDF1FPktCr2jMx17rSTYpEj2sJ1RsiLT+tnKr6GwVtU2E28LePpAzhZ6aKBCrT9H492QBo9QjzERFsSpzCEWy9gRVdTXJ4pkhhES7aG/ldRuoQ1yRDDp5kxM+vYWeQ1lozbXJN2NVyeG/6ys0XlehkU0dIgbv+nGvgVRacpFn0MI2PsJj7qNKN1JglupyeRIe6+nuL1Wxsda9dAPfG5Y9uScaIO6vje1uw5tG9afrBL4vkTMKVnL5csduQiXfSb4fJkn9SB5vNNIqVSyOFf57rkq6szby66TIh/iOmqj6FnFFmIY0QImi9ZkAk7i+Vb/ESTzfnyP48LAGx9+Gr69vBCyufZzVW74Sf7yGLxZyPJZJ3AC101xjL+FtdpWvy/dywNON2hUw5o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_4
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
