env:
  global:
    - secure: lmR1a4gHd5sS+tS14nFUjnvgeyuFMnaZHtit+4sc5RNv/CCSHmRudMmNeEquou3ZqyNgxmUJIbCC+vRTqS28PA/owKswwGbA+k0LmoJNduWe2rJ4/RoMq06jC5JorNyVDJ8Rfjt2p+6O+vXBD84RQ+Wzn2J5glF0sxgGNa450Ouwggq570Nnmk/ZfFyo6E54SIyI967VyQAzgLNihEX7cA9WBeahVjObVFeku+Mcb0ZjraB6KXf18zg2/irvCsFksHywfhP+8sunB0IgmedKiQj7bXmUkMQccQcGTd/sW3qwaUTK/brihPo13iF8xOl/h+XY7mh+zdu1j6w25tKpkIKjPKfUVLapkk0jkJUEYL8mZsj76qz9MBa4kdCkWELuhqf3pBzmx+fghRDQjUn4fkSJ4jJZ8jwMyWoGYPf61Vqo76OJRMbl4Lo7Rq5KfCpLEUDcVCF4Efx3OUounv3SUFibBp3aad0S1pih9W/KwMeMXW0IOEsJ4LNV4pLyG+kDX/2WZwjbPJJj0ltwV5982nS3yZqKyeFpoJVrugWqRYtYO5MhS414wcoYdV8W+MgYMolFNoy87pSzPmzJY+eg3mn+vG7dIbL72SN3X6QPwW8OqAU5xACgHADsk91oKfpYEoLrtbDwtlvzSROpa2gR51F/kbFrCfLf3BCYFFqPF7c=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_4
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
