env:
  global:
    - secure: eJuhTjZrUbuz4dHsM2gEm79zLjqJGBLfNuvUU0HdEq1+nXZH4UTVfUhRzHSQZr1mlbrKtem6Q8RD1NCSrx9zpAvoNRV5BmMIknQEMeyYtXeZmD+EX07LFnzBlEomU3N7zhBjS/soM3kjTGvZTPO74WqbthSKMsfthTueoMYHP+fwUSOQcKg1xZyO4Zt8BLitorLnmRg9UXKrJhCkN2M3BIDHm6PUPRZybEJdp+yBdxMf74+Qt2Ac/oJ22poreeyXP/2UcmQgPIp/PaavJyWBwbcGiEKI9++yP7FF3yaQvkWnw+xZ/7sdOIy4RDTKCjPit/zRQruSapTDj7NU9bpVxukwsT3OTiBzynXz2qCrYEC9khNxByf+4w5iBGGpR8mRfUZjasRRtnZb3vI5tGgYNM8OV72/Q5ZUa7v2HBShz/31CJMzioKVvcSq+EN6MeENI4ccMT5ygm4HhnVVUvgxwOxGsSK/9gCZprxfeWJA+awV0er+N8NL24joLGHkzNQMftY2Tk2QKLBZUUU17jtqXLQbPeuhKSoUFSa9uaWo1NhM4Hx3oHyHofjGpDwjD6PywSrb74Gc6mIQcN1ywrqScAdQ0FbW1kR1Q4pZLAJ9sR6RIf7V1Kn3heftUGsqWm/INZTqLeNm+Yj3nHgAlI9cY3zq9m1ngT5awXyNM39Iurw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_4
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
