env:
  global:
    - secure: NOsMsZ+FWSxUsug7O+imOxHNmE8m55s8ifo8hfyotkbMveAC+1HSDFYWJxp6D8GTrB8RxuzDwMlp1Exe4+hHLfRIR4mCW5YZr8jrAf0/liJvoStUhjNWHkZIeoSWgHz+9ZEGrMS3Zjzh9OKw2di/KhQTL3NkBdPTn6N0Weuwe/ftp5/sVhoNX33Rd964KX5xUDAOgypIiuPnDpfuK6qzOEOsqHmsHyqsUnkxfFcIGD9NtRFCmGiATHUF2wON25tjJwjecTRCyq+r5cf/NgOFzDsTz5bdHVeYB45Q02Hx9+uf1OaKce20gcPelb+p5KRUNuhp1JiGJ6x6PErtOfFYmw/GtcxPWTP1VO7L1PGc7JNf7KVGu18UxBGQ21LqK2O2fQ4v54QTPuT+E00cfJKKu4PSbtuDiSzxMxGyusqb0TAdUZPpfkLxqbBCtenP8IFrQmAQMc/2YOla1H+9XhHGnUqm8JYop1tQ2Pgxzr46/U4zdj8XjPB4heZL4+1EGlaUwspQcIgy1Ca4zI/p5LWfComHMMVKDqyqWL7yU7sgC9+hrEbCS22GbTAn1+UYHv2qzYuMRQxBNlVWezbMQXa5Rvufv8i3DJKrESa3tasbq7xu4qwenxUwQN5Jx5qewMOo9QipE7Qg6bD2+Bfj5yRwssOgPWr0zV18Nf43bAkeLIk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_4
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
